version: "3.9"

services:
  web:
    container_name: next-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app           # sync โค้ดในเครื่องเข้า container
      - /app/node_modules  # ให้ container ใช้ node_modules ของตัวเอง
    env_file:
      - .env.local       # เอา .env ใช้งานใน dev ได้
